### ISSUE TITLE
How to use without AppDelegate in a command line app?

### ISSUE THREAD

**Issue by vjjjv** [jdiehl/async-network#20]
We are trying to use AsyncNetwork in a native osx node.js module and cannot quite get it to work. Our node.js module does initialize the AsyncServer fine, but then no signals are ever fired..

Would it be possible to have one example without AppDelegate. I quess it would need to initialize the needed runloops and queues so that AsyncNetwork can work?

**Comment by jdiehl** [comment]
That's a tough question... AsyncNetwork relies on [CocoaAsyncSocket](https://github.com/robbiehanson/CocoaAsyncSocket) for all socket operations, including attaching operations to the run loop, so you should best ask your question there as well.

As far as I know, CocoaAsyncSocket uses a dispatch_queue to schedule all operations (not a runloop). AsyncNetwork assigns `dispatch_get_main_queue();` to CocoaAsyncSocket, which normally is scheduled in the main run loop.

It seems to me that in your setup, the main run loop does not exist and thus the main queue is never scheduled. You could try two things (neither of which might work):

1. Create your own main run loop (See [NSRunLoop](https://developer.apple.com/reference/foundation/nsrunloop)
2. Create your own dispatch queue  (See [Dispatch Queues](https://developer.apple.com/library/content/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationQueues/OperationQueues.html), make sure it works, and use it instead of the main queue (change `extern dispatch_queue_t AsyncNetworkDispatchQueue()` ind `AsyncNetworkHelpers.m`)

Hope this helps!
